# Generated by Django 5.0.6 on 2025-11-11 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_alter_commoncategory_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100, verbose_name="発生箇所")),
                (
                    "type_name",
                    models.CharField(max_length=100, verbose_name="エラー種類"),
                ),
                ("message", models.TextField(verbose_name="内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unresolved", "未対応"),
                            ("in_progress", "対応中"),
                            ("resolved", "対応済み"),
                        ],
                        default="unresolved",
                        max_length=20,
                        verbose_name="対応ステータス",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="対応メモ"),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_admin_errors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="対応者",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_error_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "エラーログ",
                "verbose_name_plural": "エラーログ",
                "ordering": ["-created_at"],
            },
        ),
    ]
