# Generated by Django 5.0.6 on 2025-11-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_errorlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errorlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "管理用エラーログ",
                "verbose_name_plural": "管理用エラーログ",
            },
        ),
    ]
