# Generated by Django 5.0.6 on 2025-11-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_alter_errorlog_options"),
        ("main", "0032_alter_pricehistory_checked_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("email", "メール"), ("app", "アプリ")], max_length=20
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mail_buy_timing", "買い時お知らせ"),
                            ("mail_stock", "在庫お知らせ"),
                            ("threshold_hit", "買い時価格"),
                            ("discount_over", "割引率"),
                            ("lowest_price", "最安値"),
                            ("stock_few", "在庫少"),
                            ("stock_restore", "在庫復活"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
