# Generated by Django 5.0.6 on 2026-05-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_notificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonCategory',
        ),
    ]
