# Generated by Django 5.2.7 on 2025-10-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='この金額以下になったら通知', max_digits=10, null=True, verbose_name='買い時価格'),
        ),
    ]
