# Generated by Django 5.2.7 on 2025-10-17 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernotificationsetting",
            options={
                "verbose_name": "ユーザー通知設定",
                "verbose_name_plural": "ユーザー通知設定",
            },
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="digest_hour",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="last_digest_sent_at",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="mode",
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="threshold_percent",
            field=models.PositiveIntegerField(
                default=90, verbose_name="買い時通知の閾値（定価比％）"
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="通知を有効にする"),
        ),
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
    ]
