# Generated by Django 5.2.7 on 2025-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_usernotificationsetting_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="threshold_percent",
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="通知メールアドレス"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="notify_hour",
            field=models.PositiveIntegerField(default=9, verbose_name="通知時刻（時）"),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="notify_minute",
            field=models.PositiveIntegerField(default=0, verbose_name="通知時刻（分）"),
        ),
    ]
