# Generated by Django 5.2.7 on 2025-10-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_usernotificationsetting_threshold_percent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={
                "ordering": ["-notified_at"],
                "verbose_name": "通知ログ",
                "verbose_name_plural": "通知ログ一覧",
            },
        ),
    ]
