# Generated by Django 5.2.7 on 2025-10-21 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_notificationlog_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("threshold_hit", "買い時価格ヒット")], max_length=64
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_events",
                        to="main.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_events",
                "indexes": [
                    models.Index(
                        fields=["user", "product", "event_type", "occurred_at"],
                        name="notificatio_user_id_7c24cf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "product", "event_type", "occurred_at"),
                        name="uniq_event_same_second",
                    )
                ],
            },
        ),
    ]
