# Generated by Django 5.2.7 on 2025-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_add_sent_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationsetting",
            name="timezone",
            field=models.CharField(
                default="Asia/Tokyo", max_length=50, verbose_name="タイムゾーン"
            ),
        ),
    ]
