# Generated by Django 5.2.7 on 2025-10-22 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usernotificationsetting_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('PRICE_BELOW', '指定価格以下'), ('STOCK_AVAILABLE', '在庫あり'), ('DISCOUNT_OVER', '割引率指定以上')], max_length=30, verbose_name='フラグ種別')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='条件値')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='main.product', verbose_name='対象商品')),
            ],
            options={
                'verbose_name': '商品通知フラグ',
                'verbose_name_plural': '商品通知フラグ',
                'db_table': 'product_flags',
            },
        ),
    ]
