# Generated by Django 5.2.7 on 2025-10-22 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': '商品通知フラグ', 'verbose_name_plural': '商品通知フラグ'},
        ),
        migrations.AddField(
            model_name='flag',
            name='flag_type',
            field=models.CharField(choices=[('PRICE_BELOW', '指定価格以下'), ('STOCK_AVAILABLE', '在庫あり'), ('DISCOUNT_OVER', '割引率指定以上')], default='PRICE_BELOW', max_length=30, verbose_name='フラグ種別'),
        ),
        migrations.AddField(
            model_name='flag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
        migrations.AddField(
            model_name='flag',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='条件値（閾値など）'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='monitor_status',
            field=models.CharField(default='monitoring', max_length=20, verbose_name='監視ステータス'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='main.product', verbose_name='対象商品'),
        ),
        migrations.DeleteModel(
            name='ProductFlag',
        ),
    ]
