# Generated by Django 5.2.7 on 2025-10-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_flag_options_flag_flag_type_flag_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flag_type',
            field=models.CharField(choices=[('PRICE_BELOW', '指定価格以下'), ('LOWEST_PRICE', '最安値更新'), ('DISCOUNT_OVER', '割引率指定以上')], default='PRICE_BELOW', max_length=30, verbose_name='フラグ種別'),
        ),
    ]
