# Generated by Django 5.2.7 on 2025-10-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_flag_flag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('threshold_hit', '買い時価格ヒット'), ('LOWEST_PRICE', '過去最安値を更新')], max_length=64),
        ),
    ]
