# Generated by Django 5.2.7 on 2025-10-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_notificationevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('threshold_hit', '買い時価格ヒット'), ('LOWEST_PRICE', '過去最安値を更新'), ('DISCOUNT_OVER', '割引率指定以上')], max_length=64),
        ),
    ]
