# Generated by Django 5.0.6 on 2025-10-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_category_is_global_alter_category_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="flag_reached",
            field=models.BooleanField(
                default=False,
                help_text="条件を満たした場合にTrue",
                verbose_name="フラグ達成状態",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("price", "価格が指定額以下"),
                    ("rate", "割引率が指定％以上"),
                    ("drop", "前回比の値下げ率が指定％以上"),
                ],
                default="price",
                help_text="どの条件で通知するかを指定（価格・割引率・値下げ率）",
                max_length=10,
                verbose_name="通知条件タイプ",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flag_value",
            field=models.FloatField(
                blank=True,
                help_text="通知条件となる金額または％（例：5000円以下、20％以上など）",
                null=True,
                verbose_name="フラグ値",
            ),
        ),
    ]
