# Generated by Django 5.0.6 on 2025-10-24 00:14

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_flag_reached_product_flag_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[main.models.validate_positive], verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[main.models.validate_positive], verbose_name='登録時価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[main.models.validate_positive], verbose_name='定価'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threshold_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='この金額以下になったら通知', max_digits=10, null=True, validators=[main.models.validate_positive], verbose_name='買い時価格'),
        ),
    ]
