# Generated by Django 5.0.6 on 2025-10-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_pricehistory_price_alter_product_initial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsetting',
            name='app_notify_frequency',
            field=models.CharField(choices=[('frequent', '多め（都度通知）'), ('daily', '少なめ（1日1回）')], default='frequent', help_text='多めは都度通知、少なめは指定時刻に1回まとめて通知', max_length=10, verbose_name='アプリ内通知頻度'),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='app_notify_hour',
            field=models.PositiveIntegerField(default=9, verbose_name='アプリ通知時刻（時）'),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='app_notify_minute',
            field=models.PositiveIntegerField(default=0, verbose_name='アプリ通知時刻（分）'),
        ),
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='メール通知を有効にする'),
        ),
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='notify_hour',
            field=models.PositiveIntegerField(default=9, verbose_name='メール通知時刻（時）'),
        ),
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='notify_minute',
            field=models.PositiveIntegerField(default=0, verbose_name='メール通知時刻（分）'),
        ),
    ]
