# Generated by Django 5.0.6 on 2025-10-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_usernotificationsetting_app_notify_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True, help_text='APIから取得した在庫情報。Falseなら一覧でグレーアウト表示', verbose_name='在庫あり'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag_type',
            field=models.CharField(choices=[('price', '価格が指定額以下'), ('rate', '割引率が指定％以上'), ('drop', '前回比の値下げ率が指定％以上'), ('restock', '在庫復活通知')], default='price', help_text='どの条件で通知するかを指定（価格・割引率・値下げ率・在庫復活）', max_length=10, verbose_name='通知条件タイプ'),
        ),
    ]
