# Generated by Django 5.0.6 on 2025-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_is_in_stock_alter_product_flag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restock_last_checked',
            field=models.DateTimeField(blank=True, help_text='在庫情報を最後に確認した日時（バッチ用）', null=True, verbose_name='最終在庫確認日時'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_notify_enabled',
            field=models.BooleanField(default=False, help_text='在庫が復活した際に通知を受け取る', verbose_name='在庫復活通知を有効にする'),
        ),
    ]
