# Generated by Django 5.0.6 on 2025-10-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_product_restock_last_checked_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={
                "ordering": ["-checked_at"],
                "verbose_name": "価格・在庫履歴",
                "verbose_name_plural": "価格・在庫履歴",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("price_drop", "価格通知"),
                    ("restock", "再入荷通知"),
                    ("stock_low", "在庫少通知"),
                ],
                default="price_drop",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="stock_count",
            field=models.IntegerField(
                blank=True,
                help_text="取得時点の在庫数（数量不明時はNULL）",
                null=True,
                verbose_name="在庫数",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="latest_stock_count",
            field=models.IntegerField(
                blank=True,
                help_text="最新の在庫数量（数量不明時はNULL）",
                null=True,
                verbose_name="最新在庫数",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="stock_low_threshold",
            field=models.PositiveIntegerField(default=5, verbose_name="在庫少通知閾値"),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("threshold_hit", "買い時価格ヒット"),
                    ("LOWEST_PRICE", "過去最安値を更新"),
                    ("DISCOUNT_OVER", "割引率指定以上"),
                    ("stock_low", "在庫少通知"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flag_reached",
            field=models.BooleanField(default=False, verbose_name="フラグ達成状態"),
        ),
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="app_notify_frequency",
            field=models.CharField(
                choices=[
                    ("frequent", "多め（都度通知）"),
                    ("daily", "少なめ（1日1回）"),
                ],
                default="frequent",
                max_length=10,
                verbose_name="アプリ内通知頻度",
            ),
        ),
        migrations.AlterModelTable(
            name="pricehistory",
            table="price_histories",
        ),
        migrations.DeleteModel(
            name="Flag",
        ),
    ]
