# Generated by Django 5.0.6 on 2025-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_pricehistory_options_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_low_threshold",
            field=models.PositiveIntegerField(
                default=5,
                help_text="この数量以下になったら在庫少通知を発行",
                verbose_name="在庫少通知閾値（商品別）",
            ),
        ),
    ]
