# Generated by Django 5.0.6 on 2025-10-25 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_product_stock_low_threshold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errorlog",
            options={"verbose_name": "エラーログ", "verbose_name_plural": "エラーログ"},
        ),
        migrations.RenameField(
            model_name="errorlog",
            old_name="occurred_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="errorlog",
            old_name="detail",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="errorlog",
            name="type",
        ),
        migrations.AddField(
            model_name="errorlog",
            name="type_name",
            field=models.CharField(default="UnknownError", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="source",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
