# Generated by Django 5.0.6 on 2025-10-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_errorlog_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="main.category",
                verbose_name="カテゴリ（複数選択可）",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("buy_price", "買い時価格で通知"),
                    ("percent_off", "割引率で通知"),
                    ("lowest_price", "最安値で通知"),
                ],
                default="buy_price",
                help_text="どの条件で通知するかを指定（買い時価格・割引率・最安値）",
                max_length=20,
                verbose_name="通知条件タイプ",
            ),
        ),
    ]
