# Generated by Django 5.0.6 on 2025-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_product_category_product_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationevent",
            options={
                "verbose_name": "通知イベント",
                "verbose_name_plural": "通知イベント一覧",
            },
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("threshold_hit", "買い時価格ヒット"),
                    ("lowest_price", "過去最安値を更新"),
                    ("discount_over", "割引率指定以上"),
                    ("stock_low", "在庫少通知"),
                    ("restock", "在庫復活通知"),
                ],
                max_length=64,
            ),
        ),
    ]
