# Generated by Django 5.0.6 on 2025-11-08 06:49

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_product_common_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="product",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationlog",
            name="product",
        ),
        migrations.RemoveField(
            model_name="notificationlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationsetting",
            name="product",
        ),
        migrations.RemoveField(
            model_name="notificationsetting",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="errorlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "エラーログ",
                "verbose_name_plural": "エラーログ",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationevent",
            options={
                "ordering": ["-occurred_at"],
                "verbose_name": "通知イベント",
                "verbose_name_plural": "通知イベント",
            },
        ),
        migrations.AlterModelOptions(
            name="pricehistory",
            options={
                "ordering": ["-checked_at"],
                "verbose_name": "価格履歴",
                "verbose_name_plural": "価格履歴",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
        migrations.AlterModelOptions(
            name="usernotificationsetting",
            options={"verbose_name": "通知設定", "verbose_name_plural": "通知設定"},
        ),
        migrations.RemoveConstraint(
            model_name="notificationevent",
            name="uniq_event_same_second",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="uq_user_producturl",
        ),
        migrations.RemoveIndex(
            model_name="notificationevent",
            name="notificatio_user_id_7c24cf_idx",
        ),
        migrations.RemoveField(
            model_name="notificationevent",
            name="sent_at",
        ),
        migrations.RemoveField(
            model_name="notificationevent",
            name="sent_flag",
        ),
        migrations.RemoveField(
            model_name="product",
            name="common_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="flag_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="flag_value",
        ),
        migrations.RemoveField(
            model_name="product",
            name="regular_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="restock_last_checked",
        ),
        migrations.RemoveField(
            model_name="product",
            name="restock_notify_enabled",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_low_threshold",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="app_notify_frequency",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="app_notify_hour",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="app_notify_minute",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="stock_low_threshold",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="timezone",
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="既読"),
        ),
        migrations.AddField(
            model_name="product",
            name="latest_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                validators=[main.models.validate_positive],
                verbose_name="最新価格",
            ),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="message",
            field=models.TextField(verbose_name="エラーメッセージ"),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="source",
            field=models.CharField(max_length=100, verbose_name="発生箇所"),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="type_name",
            field=models.CharField(max_length=100, verbose_name="例外名"),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(max_length=50, verbose_name="イベント種別"),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="message",
            field=models.TextField(blank=True, verbose_name="通知内容"),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="occurred_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="発生日時"),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_histories",
                to="main.product",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="stock_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="在庫数"),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="main.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flag_reached",
            field=models.BooleanField(default=False, verbose_name="買い時達成"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="商品画像URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_in_stock",
            field=models.BooleanField(default=True, verbose_name="在庫あり"),
        ),
        migrations.AlterField(
            model_name="product",
            name="latest_stock_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="最新在庫数"),
        ),
        migrations.AlterField(
            model_name="product",
            name="priority",
            field=models.CharField(
                choices=[("普通", "普通"), ("高", "高")],
                default="普通",
                max_length=10,
                verbose_name="優先度",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="商品名"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_url",
            field=models.URLField(verbose_name="商品URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="threshold_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                validators=[main.models.validate_positive],
                verbose_name="買い時価格",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="notify_hour",
            field=models.PositiveIntegerField(default=9, verbose_name="通知時刻（時）"),
        ),
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="notify_minute",
            field=models.PositiveIntegerField(default=0, verbose_name="通知時刻（分）"),
        ),
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_setting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("user", "product_url"), name="uq_user_product_url"
            ),
        ),
        migrations.AlterModelTable(
            name="errorlog",
            table=None,
        ),
        migrations.AlterModelTable(
            name="notificationevent",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pricehistory",
            table=None,
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
        migrations.AlterModelTable(
            name="usernotificationsetting",
            table=None,
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationLog",
        ),
        migrations.DeleteModel(
            name="NotificationSetting",
        ),
    ]
