# Generated by Django 5.0.6 on 2025-11-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_notification_product_remove_notification_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="flag_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buy_price", "買い時価格"),
                    ("percent_off", "割引後価格"),
                    ("lowest_price", "最安値"),
                ],
                help_text="買い時価格／割引後価格／最安値のいずれかを指定",
                max_length=20,
                null=True,
                verbose_name="買い時条件タイプ",
            ),
        ),
    ]
