# Generated by Django 5.0.6 on 2025-11-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_product_flag_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="flag_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="買い時価格・割引率・最安値の基準値（flag_typeに応じて解釈）",
                max_digits=5,
                null=True,
                verbose_name="通知条件値",
            ),
        ),
    ]
