# Generated by Django 5.0.6 on 2025-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_product_flag_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="flag_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="買い時価格・割引率・最安値の基準値（flag_typeに応じて解釈）",
                max_digits=10,
                null=True,
                verbose_name="通知条件値",
            ),
        ),
    ]
