# Generated by Django 5.0.6 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_product_flag_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="checked_at",
            field=models.DateTimeField(verbose_name="取得日時"),
        ),
    ]
