# Generated by Django 5.0.6 on 2025-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_pricehistory_checked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("stock_few", "在庫少通知"),
                    ("stock_restore", "在庫復活通知"),
                    ("threshold_hit", "買い時価格検知"),
                    ("discount_over", "指定割引率下回り"),
                    ("lowest_price", "過去最安値更新"),
                ],
                max_length=50,
                verbose_name="イベント種別",
            ),
        ),
    ]
