# Generated by Django 5.0.6 on 2025-11-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_notificationevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="削除フラグ"),
        ),
        migrations.AlterField(
            model_name="product",
            name="flag_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buy_price", "買い時価格"),
                    ("percent_off", "割引率"),
                    ("lowest_price", "最安値"),
                ],
                help_text="買い時価格／割引率／最安値のいずれかを指定",
                max_length=20,
                null=True,
                verbose_name="買い時条件タイプ",
            ),
        ),
    ]
