# Generated by Django 5.0.6 on 2025-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0007_notificationlog"),
        ("main", "0035_alter_product_user_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="common_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="共通カテゴリマスタとの紐付け",
                related_name="products",
                to="admin_app.commoncategory",
                verbose_name="共通カテゴリ",
            ),
        ),
    ]
