# Generated by Django 5.0.6 on 2025-11-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_product_common_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationsetting",
            name="app_notify_frequency",
            field=models.CharField(
                choices=[("多め", "多め"), ("少なめ", "少なめ")],
                default="多め",
                max_length=10,
                verbose_name="アプリ内通知頻度",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="app_notify_hour",
            field=models.PositiveIntegerField(
                default=9, verbose_name="アプリ内通知時刻（時）"
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="app_notify_minute",
            field=models.PositiveIntegerField(
                default=0, verbose_name="アプリ内通知時刻（分）"
            ),
        ),
    ]
