# Generated by Django 5.0.6 on 2025-11-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_usernotificationsetting_app_notify_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="app_notify_frequency",
            field=models.CharField(
                choices=[("多め", "多め"), ("少なめ", "少なめ")],
                default="多め",
                help_text="「多め」は買い時検知のたびに通知、「少なめ」は指定時刻に1回まとめて通知",
                max_length=10,
                verbose_name="アプリ内通知頻度",
            ),
        ),
    ]
