# Generated by Django 5.0.6 on 2025-11-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_alter_usernotificationsetting_app_notify_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="app_notify_frequency",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="app_notify_hour",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="app_notify_minute",
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="notification_retention_days",
            field=models.PositiveIntegerField(
                choices=[(7, "7日間"), (30, "30日間"), (365, "無制限")],
                default=7,
                help_text="指定日数を過ぎた通知は自動的に既読になります",
                verbose_name="通知の保持期間（日）",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="notify_buy_time_only",
            field=models.BooleanField(
                default=False,
                help_text="チェックすると、買い時以外の通知（在庫復活など）は表示されません",
                verbose_name="買い時価格到達時のみ通知する",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="notify_high_priority_only",
            field=models.BooleanField(
                default=False,
                help_text="チェックすると、優先度「普通」の商品は通知されません",
                verbose_name="優先度「高」の商品のみ通知する",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="notify_stock_restore",
            field=models.BooleanField(
                default=True,
                help_text="在庫切れ商品が復活したときに通知します",
                verbose_name="在庫復活時も通知する",
            ),
        ),
    ]
