# Generated by Django 5.0.6 on 2025-11-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_remove_usernotificationsetting_app_notify_frequency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="notify_buy_time_only",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="notify_high_priority_only",
        ),
        migrations.RemoveField(
            model_name="usernotificationsetting",
            name="notify_stock_restore",
        ),
        migrations.AddField(
            model_name="usernotificationsetting",
            name="app_notification_enabled",
            field=models.BooleanField(
                default=True,
                help_text="優先度「高」の商品の買い時通知・在庫通知を受け取ります",
                verbose_name="アプリ内通知を有効にする",
            ),
        ),
    ]
