# Generated by Django 5.0.6 on 2026-05-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_usernotificationsetting_notify_buy_time_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='common_categories',
        ),
    ]
