# Generated by Django 5.0.6 on 2026-05-15 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_product_common_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_errors', to=settings.AUTH_USER_MODEL, verbose_name='対応者'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='対応メモ'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='status',
            field=models.CharField(choices=[('unresolved', '未対応'), ('in_progress', '対応中'), ('resolved', '対応済み')], default='unresolved', max_length=20, verbose_name='対応ステータス'),
        ),
    ]
