# Generated by Django 5.0.6 on 2026-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_errorlog_handled_by_errorlog_note_errorlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='sent_flag',
            field=models.BooleanField(default=False, verbose_name='メール送信済み'),
        ),
    ]
