# Generated by Django 5.0.6 on 2026-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_notificationevent_sent_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('stock_few', '在庫少通知'), ('stock_restore', '在庫復活通知'), ('stock_none', '売り切れ通知'), ('threshold_hit', '買い時価格検知'), ('discount_over', '指定割引率下回り'), ('lowest_price', '過去最安値更新')], max_length=50, verbose_name='イベント種別'),
        ),
    ]
